#!/bin/bash

MIRROR_DIR=$HOME/.mirror

docker kill web

docker run -d \
    --name="mirror" \
    --volume="$MIRROR_DIR:/root/.mirror/:rw" \
    --rm \
    java
    
docker run \
    --name="web" \
    --net=host \
    --volume="$MIRROR_DIR:/root/.mirror:rw" \
    --rm \
    web


