#!/bin/bash

# Build and run python and java containers
docker-compose up -d --build

# Get machine IP for web service access
export PORT=8080
case $OSTYPE in
    linux*) # Linux
		if [ "$(whoami)" == "pi" ]
		then
			IFACE="wlan0"
		else
			IFACE="enp0s31f6"
		fi
		export IP=$(/sbin/ifconfig $IFACE | awk '/inet /{print substr($2, 1)}')
        export WEBADDRESS=$IP:$PORT
        ;;
    darwin*) # MacOS
		export IP=$(/sbin/ifconfig en0 | awk '/inet /{print substr($2, 1)}')
        export WEBADDRESS=$IP:$PORT
        ;;
    *)
esac
echo "Web Address: $WEBADDRESS"

# Set paths for the config file and Java watcher
export CONFIGPATH=$HOME/.mirror/mirror_config.xml
export WATCHPATH=$HOME/.mirror/

# Get arguments
for var in "$@"
do
	case $var in
		"-sw")
			SW="-Dprism.order=sw"
			echo "Using Software Rendering"
			;;
		"-fullscreen")
			FULLSCREEN=$var
			echo "Launching Fullscreen"
			;;
		*)
	esac
done

java $sw --module-path $HOME/.mirror/lib/ --add-modules javafx.controls,javafx.fxml -jar $HOME/.mirror/smart-mirror-1.0.jar $FULLSCREEN
