#!/bin/bash

export WEBADDRESS=$(ip route get 1.1.1.1 | grep -oP 'src \K\S+'):8080
export CONFIGPATH_PY=/root/.mirror/mirror_config.xml

# Build and run python and java containers
docker-compose up -d --build

# Get arguments
for var in "$@"
do
	case $var in
		"-sw")
			SW="-Dprism.order=sw"
			echo "Using Software Rendering"
			;;
		"-fullscreen")
			FULLSCREEN=$var
			echo "Launching Fullscreen"
			;;
		*)
	esac
done

export CONFIGPATH=$HOME/.mirror/mirror_config.xml
export WATCHPATH=$HOME/.mirror/

if [ -d /usr/share/openjfx ]
then
    JFXLIB=/usr/share/openjfx/lib
    echo "Using OpenJFX libraries"
else
    JFXLIB=$HOME/.mirror/lib  
fi

java $sw --module-path $JFXLIB --add-modules javafx.controls,javafx.fxml -jar $HOME/.mirror/smart-mirror-1.0.jar $FULLSCREEN
