#!/bin/bash

# Build and run python and java containers
docker-compose up -d --build

# Set paths for the web address, config file, and Java watcher
export WEBADDRESS=$(ip route get 1.1.1.1 | grep -oP 'src \K\S+')
export CONFIGPATH=$HOME/.mirror/mirror_config.xml
export WATCHPATH=$HOME/.mirror/

# Get arguments
for var in "$@"
do
	case $var in
		"-sw")
			SW="-Dprism.order=sw"
			echo "Using Software Rendering"
			;;
		"-fullscreen")
			FULLSCREEN=$var
			echo "Launching Fullscreen"
			;;
		*)
	esac
done

java $sw --module-path $HOME/.mirror/lib/ --add-modules javafx.controls,javafx.fxml -jar $HOME/.mirror/smart-mirror-1.0.jar $FULLSCREEN
