#!/bin/bash

if [ "$EUID" -ne 0 ]
then
	echo "Please run setup with sudo or as root"
	exit 1
fi

sudo pip install Flask
sudo pip install Flask-SocketIO
sudo apt-get install python-dev
sudo pip install greenlet
sudo pip install eventlet
sudo apt-get install figlet
