#!/bin/bash

# Get web server packages
sudo pip install Flask
sudo pip install Flask-SocketIO
sudo apt-get install python-dev
sudo pip install greenlet

sudo apt-get install figlet
sudo apt-get install screen
