#!/bin/bash

# Kill any running python or java procs
./kill-mirror

# Application banner
figlet -f big 'smart  mirror'

# Get and print web service address
case $OSTYPE in
    linux*) # Linux
        export WEBADDRESS=$(ifconfig wlan0 | awk '/inet addr/{print substr($2, 6)}'):8080
        ;;
    darwin*) # MacOS
        export WEBADDRESS=$(ifconfig en0 | awk '/inet /{print substr($2, 1)}'):8080
        ;;
    *)
esac

echo Web service running on $WEBADDRESS

# Get arguments
for var in "$@"
do
	case $var in
		"-sw")
			sw="-Dprism.order=sw"
			echo "Using Software Rendering"
			;;
		"-fullscreen")
			fullscreen=$var
			echo "Launching Fullscreen"
			;;
		*)
	esac
done

# Start web service and mirror application
cd web-service
python main.py --path ../resources/mirror_config.xml &
cd ..
java $sw -jar smart-mirror.jar -jarRun $fullscreen > log.txt

# Kill all python and java when exiting
./kill-mirror
