#!/bin/bash

# Kill any running python or java procs
./kill-mirror

# Get arguments
for var in "$@"
do
	case $var in
		"-sw")
			sw="-Dprism.order=sw"
			echo "USING SOFTWARE RENDERING"
			;;
		"-fullscreen")
			fullscreen=$var
			;;
		*)
	esac
done

# Application banner
figlet -f big 'smart  mirror'

# Print webserver address
address=$(ifconfig wlan0 | awk '/inet addr/{print substr($2, 6)}'):8080
echo 'Web service running on $address'

# Start web server and javafx
cd web-service
python main.py --path ../resources/mirror_config.xml &
cd ..
java $sw -jar smart-mirror.jar -jarRun $fullscreen

# Kill all python and java when exiting
./kill-mirror
