#!/bin/bash

./killmirror

# Application banner
figlet -f big 'smart  mirror'

# Get and print web service address
export PORT=8080
case $OSTYPE in
    linux*) # Linux
		export IP=$(/sbin/ifconfig wlan0 | awk '/inet addr:/{print substr($2, 6)}')
        export WEBADDRESS=$IP:$PORT
        ;;
    darwin*) # MacOS
		export IP=$(/sbin/ifconfig en0 | awk '/inet /{print substr($2, 1)}')
        export WEBADDRESS=$IP:$PORT
        ;;
    *)
esac

# Set paths for the config file and Java watcher
export CONFIGPATH=resources/mirror_config.xml
export WATCHPATH=resources

# Get arguments
for var in "$@"
do
	case $var in
		"-sw")
			sw="-Dprism.order=sw"
			echo "Using Software Rendering"
			;;
		"-fullscreen")
			fullscreen=$var
			echo "Launching Fullscreen"
			;;
		*)
	esac
done

echo "Debug messages in log.txt"
java $sw -jar smart-mirror-1.0.jar $fullscreen &> log.txt &
cd web-service
python main.py --path ../resources/mirror_config.xml


